<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- Generated by NCL Eclipse -->
<ncl id="exemplo1" xmlns="http://www.ncl.org.br/NCL3.0/EDTVProfile">
	<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	 !					CABE�ALHO DO PROGRAMA						 !
	 !+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
	<head>
	<!--++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	 !						BASE DE REGI�ES							 !
	 !	 define as regi�es na tela onde as m�dias ser�o mostradas	 !						 
	 !+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
		<regionBase>
			<region id="regiaoBackground"/>
			<region width="10%" height="10%" left="85%" top="3%" id="regiaoBotaoInt"/>
			<region id="regiaoLogo"/>
			<region id="regiaoTelaInicial"/>
			<region id="regitaoNavegacao" width="30%" height="12%" left="67%" top="75%"/>
			<region id="regiaoBotaoIdioma" width="8%" height="3.5%" left="89%" top="89%"/>
			<region id="regiaoBotaoSair" width="8%" height="3.5%" left="78.3%" top="89%"/>
			<region id="regiaoBotaoSobre" width="8%" height="3.5%" left="67%" top="89%"/>
			<region id="regiaoTituloPreviewCidade" width="20%" height="8%" left="10%" top="21%"/>
			<region id="regiaoDescricaoPreviewCidade" width="20%" height="8%" left="10%" top="48%"/>
			<region width="50%"  height="50%"  right="25%" top="25%" id="rgLua" />
		</regionBase>
	<!--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	 !						BASE DE DESCRITORES						 !
	 !	 		define como as m�dias ser�o apresentadas			 !						 
	 !+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
		<descriptorBase>
			<descriptor id="idImagemBackground" region="regiaoBackground"/>
			<descriptor id="idBotaoInt" region="regiaoBotaoInt"/>
			<descriptor id="idLogo" region="regiaoLogo"/>
			<descriptor id="idTelaInicial" region="regiaoTelaInicial"/>
			<descriptor id="idNavegacao" region="regitaoNavegacao"/>
			<descriptor id="idBotaoIdioma" region="regiaoBotaoIdioma" focusBorderWidth="2"/>
			<descriptor id="idBotaoSair" region="regiaoBotaoSair" />
			<descriptor id="idBotaoSobre" region="regiaoBotaoSobre"/>
			<descriptor id="idTituloPreviewCidade" region="regiaoTituloPreviewCidade"/>
			<descriptor id="idDescricaoPreviewCidade" region="regiaoDescricaoPreviewCidade"/>
			<descriptor id="dsLua" region="rgLua" focusIndex="1" focusBorderWidth="5" />
		</descriptorBase>
	<!--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	 !						BASE DE CONECTORES						 !
	 !	 			definem o comportamento dos elos				 !						 
	 !+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
		<connectorBase>
			<importBase documentURI="connectorBaseTelaInicial.ncl" alias="conectores"/>
		</connectorBase>
	</head>
	<!--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	 !						CORPO DO PROGRAMA						 !
	 !	 		define as m�dias e a estrutura do programa			 !						 
	 !+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
	<body id="teste">
	<!--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	 !						PONTO DE ENTRADA						 !
	 !	 		indica o componente onde o programa inicia			 !						 
	 !+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
		<port id="porta1" component="imagemBackground"/>
	<!--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	 !						M�DIAS						             !
	 ! 	  define o local dos arquivos de m�dia e as associa a seus   !
	 !					 	descritores								 !						 
	 !+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
		<media id="imagemBackground" src="media/BackgroundInicio.jpg" descriptor="idImagemBackground"/>
		<media id="botaoInt" src="media/BotaoInterativo.png" descriptor="idBotaoInt"/>
		<media id="logo" src="media/logo.png" descriptor="idLogo">
			<area id="aLogoInicio" begin="1s" end="30s"/>
		</media>
		<media id="telaInicial" src="media/telaInicial.png" descriptor="idTelaInicial"/>
		<media id="painelNavegacao" src="media/navegacao.png" descriptor="idNavegacao"/>
		<media id="botaoIdioma" src="media/botaoIdioma.png" descriptor="idBotaoIdioma">
			<property name="focusIndex" value="0"/>
		</media>
			
		<media id="botaoSair" src="media/botaoSair.png" descriptor="idBotaoSair"/>
		<media id="botaoSobre" src="media/botaoSobre.png" descriptor="idBotaoSobre"/>
		<media id="tituloPreviewCidade" src="media/cidadePreviewTitulo.png" descriptor="idTituloPreviewCidade"/>
		<media id="descricaoPreviewCidade" src="media/descricaoPreviewCidade.png" descriptor="idDescricaoPreviewCidade"/>
		<media id="settings" type="application/x-ginga-settings">
		<property name="service.currentKeyMaster" value=""/>
 		</media>
		<media id="lua" src="Lua/dialogo.lua" descriptor="dsLua"/>
	<!--+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
	 !						ELOS						             !
	 ! 	  define os elos que regem o sincronismo entre as m�dias     !					 
	 !+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
		<!-- exibe a imagem de background juntamente com o bot�o de intera��o -->
		<link id="lImagBotaoIntAparece" xconnector="conectores#noInicio">
			<bind role="onBegin" component="imagemBackground"/>
			<bind role="start" component="botaoInt"/>
		</link>
		<link id="lImagBotaoIntDesaparece" xconnector="conectores#noFim">
			<bind role="onEnd" component="imagemBackground"/>
			<bind role="stop" component="imagemBackground"/>
			<bind role="stop" component="logo"/>
		</link>
		<!-- exibe a tela inicial ap�s a exibi��o de alguns segundos do logo -->
		<link xconnector="conectores#noInicio" id="ltelaInicialAparece">
			<bind role="onBegin" interface="aLogoInicio" component="logo"/>
			<bind role="start" component="telaInicial"/>
			<bind role="stop" component="botaoInt"/>
		</link>
		<!-- exibe todos os componentes da tela inicial -->
		<link xconnector="conectores#noInicio" id="ltelaInicialFixa">
			<bind role="onBegin" component="telaInicial"/>
			<bind role="start" component="painelNavegacao"/>
			<bind role="start" component="botaoIdioma" interface="focusIndex" />
			<bind role="start" component="botaoSair"/>
			<bind role="start" component="botaoSobre"/>
			<bind role="start" component="tituloPreviewCidade"/>
			<bind role="start" component="descricaoPreviewCidade"/>
		</link>
		<!-- exibe o logo ap�s a sele��o do bot�o de intera��o -->
		<link id="lSelecionaBotaoInt" xconnector="conectores#selecaoBotaoIntInicioFim">
			<bind role="onSelection" component="botaoInt">
				<bindParam name="keyCode" value="RED"/>
			</bind>
			<bind component="botaoInt" role="stop"/>
			<bind component="botaoInt" role="abort"/>
			<bind component="logo" role="start"/>
		</link>
		
		<link id="lSelecionaBotaoLua" xconnector="conectores#onKeySelectionStart">
			<bind role="onSelection" component="botaoSobre">
				<bindParam name="key" value="GREEN"/>
			</bind>
			<bind component="lua" role="start"/>
		</link>
		
		<link id="luaStart" xconnector="conectores#onBeginSet">
			<bind role="onBegin" component="lua" />
			<bind role="set" component="settings" interface="service.currentKeyMaster">
			<bindParam name="value" value="lua"/>
			</bind>
 		</link>
 		
 		 <link xconnector="conectores#onEndStopSet">
	         <bind component="lua" role="onEnd"/>
	         
	         <bind role="set" component="settings" interface="service.currentKeyMaster">
				<bindParam name="value" value=""/>
			 </bind>	
			 <bind component="lua" role="stop"/>
		  </link>
 		
 		  <link xconnector="conectores#onAbortStop">
         <bind component="lua" role="onAbort"/>
         <bind component="teste" role="stop"/>
		  </link>
	</body>
</ncl>
